name: Branching

on:
  push:
    branches:
      - master

jobs:
  Deployment:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1

      - name: Install packages
        run: npm install

      - name: Run all tests, DO NOT deploy if they fail
        run: npm run test

      - name: Prepare the build
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build